# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "hadrian-sandbox-terraform-state-bucket"
    encrypt = true
    key     = "./terraform.tfstate"
    region  = "eu-west-1"
  }
}
