# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "sem-sandbox-terraform-state-bucket"
    encrypt = true
    key     = "sandbox/ssm/terraform.tfstate"
    region  = "eu-west-1"
  }
}
